import type { Metadata } from "next";
import "./globals.css";

import { Space_Grotesk, Bakbak_One } from 'next/font/google';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300','400','500','600','700']
});

const bakbakOne = Bakbak_One({
  subsets: ['latin'],
  weight: ['400'] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceGrotesk.className}`}>
      <body className={`${spaceGrotesk.className}`}>
        {children}
      </body>
    </html>
  );
}
