"""Add hashed_password to users and make provider fields nullable

Revision ID: 3ba62beace9a
Revises: 7dbc1747e570
Create Date: 2025-09-11 11:19:52.543764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba62beace9a'
down_revision: Union[str, Sequence[str], None] = '7dbc1747e570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
